<?php
/**
 * @category    design
 * @package     foo
 */
?>
<?php
/**
 * Edit ticket template
 *
 * @see Ticket_Manager_Block_Action_Edit
 */
?>
<div class="page-title">
    <h1><?php echo $this->getTitle() ?></h1>
</div>
<?php echo $this->getMessagesBlock()->toHtml() ?>

<form action="<?php echo Mage::getUrl('*/ticket/save', array('_secure'=>true)); ?>" method="post" id="form-validate">
    <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey')?>
        <h2 class="legend"><?php echo $this->__('Ticket Information'); ?></h2>
        <ul class="form-list">
            <li class="fields">
                <div>
                    <input type="hidden" name="id" value="<?php echo ($this->getTicket()) ? $this->getTicket()->getId() : null; ?>">
                    <div class="field name-subject">
                        <label for="subject" class="required"><em>*</em><?php echo $this->__('Subject') ?></label>
                        <div class="input-box">
                            <input type="text" id="subject" name="subject" value="<?php echo $this->escapeHtml(($this->getTicket()) ? $this->getTicket()->getSubject() : null); ?>" maxlength="255" class="input-text required-entry" />
                        </div>
                    </div>
                    <div class="field name-message">
                        <label for="message" class="required"><em>*</em><?php echo $this->__('Message') ?></label>
                        <div class="input-box">
                            <textarea id="message" name="message" class="input-text required-entry"><?php echo $this->escapeHtml(($this->getTicket()) ? $this->getTicket()->getMessage() : null); ?></textarea>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
    </div>

    <p class="required"><?php echo $this->__('* Required Fields') ?></p>

    <div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getUrl('*/')) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button data-action="save-ticket" type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Save Ticket')) ?>" class="button"><span><?php echo $this->__('Save Ticket') ?></span></button>
    </div>
</form>

<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    //]]>
</script>

