<?php
/**
 * @category    design
 * @package     foo
 */
?>
<?php
/**
 * @var $this Ticket_Manager_Block_Dashboard_List
 */
?>

<?php $_tickets = $this->getTickets();  ?>
<?php echo $this->getPagerHtml(); ?>
<table class="data-table tickets">
    <thead>
        <tr>
            <th>#</th>
            <th><?php echo $this->__('Support'); ?> ID</th>
            <th><?php echo $this->__('Subject'); ?></th>
            <th><?php echo $this->__('Status'); ?></th>
            <th><?php echo $this->__('Actions'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php $rowCount = 1; ?>
        <?php foreach ($_tickets as $ticket) : ?>
            <tr class="<?php echo ($rowCount%2==0) ? 'even' : 'odd'; ?>">
                <td><?php echo $rowCount; ?></td>
                <td class="js-ticket-id">
                    <a href="<?php echo Mage::getUrl('*/ticket/view/id/'.$ticket->getData('entity_id')); ?>">
                        <?php echo $this->escapeHtml($ticket->getSupportId()); ?>
                    </a>
                </td>
                <td><?php echo $this->escapeHtml($ticket->getSubject()); ?></td>
                <td class="js-ticket-status" style="color:<?php echo $ticket['active'] ? 'red' : 'green'; ?>"><?php echo $ticket->getActive() ? 'Opened' : 'Resolved'; ?></td>
                <td class="js-ticket-actions">
                    <?php if($ticket['active']) : ?>
                    <span style="margin:5px;">
                        <a href="<?php echo Mage::getUrl('*/ticket/close/', array('id' => $ticket->getEntityId())); ?>" class="js-ticket-action" data-action="close" title="Close this ticket">✓</a>
                    </span>
                    <?php endif; ?>
                    <span style="margin:5px;">
                        <a href="<?php echo Mage::getUrl('*/ticket/delete/', array('id' => $ticket->getEntityId())); ?>" class="js-ticket-action" data-action="delete" title="Delete this ticket">x</a>
                    </span>
                </td>
             </tr>
            <?php $rowCount++; ?>
        <?php endforeach; ?>
    </tbody>
</table>
<?php echo $this->getPagerHtml(); ?>
